import chapeu from "../img/roupas/chapeu.png";
import brinco from "../img/roupas/brinco.png";
import camiseta from "../img/roupas/camiseta.png";
import oculos from "../img/roupas/oculos-de-sol.png";
export const roupas = [
  {
    id: "1",
    pt: "Chapéu",
    jpn: "bōshi",
    kana: "ぼうし",
    kanji: "帽子",
    img: chapeu,
  },
  {
    id: "2",
    pt: "Camisa",
    jpn: "shatsu",
    kana: "シャツ",
    kanji: "",
    img: camiseta,
  },
  {
    id: "3",
    pt: "Brincos",
    jpn: "piasu",
    kana: "ピアス",
    kanji: "",
    img: brinco,
  },
  {
    id: "4",
    pt: "Óculos",
    jpn: "megane",
    kana: "めがね",
    kanji: "眼鏡",
    img: oculos,
  },
  {
    id: "5",
    pt: "Colar",
    jpn: "nekkuresu",
    kana: "ネックレス",
    kanji: "",
    img: colar,
  },
  {
    id: "6",
    pt: "Camisa",
    jpn: "shatsu",
    kana: "シャツ",
    kanji: "",
    img: camisa,
  },
  {
    id: "7",
    pt: "Blusa",
    jpn: "burausu",
    kana: "ブラウス",
    kanji: "",
    img: blusa,
  },
  {
    id: "8",
    pt: "Moletom com Capuz",
    jpn: "toreenaa",
    kana: "トレーナー",
    kanji: "",
    img: toreenaa,
  },
  {
    id: "9",
    pt: "Casaco",
    jpn: "jaketto",
    kana: "ジャケット",
    kanji: "",
    img: jaqueta,
  },
  {
    id: "10",
    pt: "Luvas",
    jpn: "tebukuro",
    kana: "てぶくろ",
    kanji: "手袋",
    img: luvas,
  },
  {
    id: "11",
    pt: "Echarpe",
    jpn: "sukaafu",
    kana: "スカーフ",
    kanji: "",
    img: encharpe,
  },
  {
    id: "12",
    pt: "Cinto",
    jpn: "beruto",
    kana: "ベルト",
    kanji: "",
    img: cinto,
  },
  {
    id: "13",
    pt: "Jeans",
    jpn: "jiinzu",
    kana: "ジーンズ",
    kanji: "",
    img: jeans,
  },
  {
    id: "14",
    pt: "Calças",
    jpn: "zubon",
    kana: "ズボン",
    kanji: "",
    img: calcas,
  },
  {
    id: "15",
    pt: "Sapatos",
    jpn: "kutsu",
    kana: "くつ",
    kanji: "靴",
    img: sapato,
  },
  {
    id: "16",
    pt: "Meias",
    jpn: "kutsushita",
    kana: "くつした",
    kanji: "靴下",
    img: meias,
  },
  {
    id: "17",
    pt: "Relógio",
    jpn: "tokei",
    kana: "とけい",
    kanji: "時計",
    img: relogio,
  },
  {
    id: "18",
    pt: "Anel",
    jpn: "yubiwa",
    kana: "ゆびわ",
    kanji: "指輪",
    img: anel,
  },
  {
    id: "19",
    pt: "Terno",
    jpn: "suutsu",
    kana: "スーツ",
    kanji: "",
    img: terno,
  },
  {
    id: "20",
    pt: "Kimono",
    jpn: "kimono",
    kana: "きもの",
    kanji: "着物",
    img: kimono,
  },
  {
    id: "21",
    pt: "Yukata",
    jpn: "kimono",
    kana: "ゆかた",
    kanji: "浴衣",
    img: yukata,
  },
  {
    id: "22",
    pt: "Sandálias",
    jpn: "sandaru",
    kana: "サンダル",
    kanji: "",
    img: sandalia,
  },
];
